getwd()
setwd("/Users/krishna/MOOC/Edge/Data")
IBM = read.csv("IBMStock.csv")
GE = read.csv("GEStock.csv")
ProcterGamble = read.csv("ProcterGambleStock.csv")
CocaCola = read.csv("CocaColaStock.csv")
Boeing = read.csv("BoeingStock.csv")
summary(IBM)
head(IBM)
mean(IBM$StockPrice)
min(GE$StockPrice)
max(CocaCola$StockPrice)
median(Boeing$StockPrice)
sd(ProcterGamble$StockPrice)

# Plot
plot(IBM$StockPrice,IBM$Date,"l")
plot(CocaCola$Date,CocaCola$StockPrice, type="l", col="red")
plot(CocaCola$Date,CocaCola$StockPrice, type="l", col="red")
