setwd("/Users/krishna/MOOC/Edge/Data")
flower = read.csv("flower.csv",header =F)
str(flower)
flowerM = as.matrix(flower)
str(flowerM)
flowerV = as.vector(flowerM)
str(flowerV)
flowerV2 = as.vector(flower)
str(flowerV2)
distance = dist(flowerV, method = "euclidean")
clusterIntensity = hclust(distance, method = "ward.D")
plot(clusterIntensity)
rect.hclust(clusterIntensity, k=3,border = "red")
flowerClusters = cutree(clusterIntensity, k=3)
flowerClusters
tapply(flowerV, flowerClusters, mean)
dim(flowerClusters) = c(50,50)
str(flowerClusters)
image(flowerClusters,axes=F)
image(flowerM,axes=F,col = grey(seq(0,1,length=256)))
